server:
  port: 8001
spring:
  thymeleaf:
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    prefix:
      classpath: /templates
  mvc:
    static-path-pattern: /static/**
